# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

# Default build settings
[build]
  publish = "public"
  command = "npm i && npm install postcss-cli && hugo"

# "production" environment specific build settings
[context.production.environment]
  HUGO_VERSION = "v0.157.0"
  HUGO_THEME = "docsy"

[context.deploy-preview]
  command = "npm i && npm install postcss-cli && hugo --buildFuture -b $DEPLOY_PRIME_URL"
